# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:nightly

    env:
      DOLFINX_CMAKE_BUILD_TYPE: Debug

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Run demos (serial)
        run: |
          python3 hdg_poisson.py
          python3 lagrange_multiplier.py
          python3 lagrange_multiplier_bc.py
          # python3 mhd.py
          python3 nested_submeshes.py
          python3 neumann_bc.py
          python3 hdg_navier_stokes.py
          python3 poisson_domain_decomp.py
          python3 cg_dg_advec_diffusion.py
          python3 buoyancy_driven_flow.py
          python3 projection.py

      - name: Run demos (parallel)
        run: |
          mpirun -n 2 python3 hdg_poisson.py
          mpirun -n 2 python3 lagrange_multiplier.py
          mpirun -n 2 python3 lagrange_multiplier_bc.py
          # mpirun -n 2 python3 mhd.py
          mpirun -n 2 python3 nested_submeshes.py
          mpirun -n 2 python3 neumann_bc.py
          mpirun -n 2 python3 hdg_navier_stokes.py
          mpirun -n 2 python3 poisson_domain_decomp.py
          mpirun -n 2 python3 cg_dg_advec_diffusion.py
          mpirun -n 2 python3 buoyancy_driven_flow.py
          mpirun -n 2 python3 projection.py
