# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dolfinx/dev-env:nightly

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          repository: FEniCS/basix
          ref: main

      # Runs a single command using the runners shell
      - name: Install basix
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=${DOLFINX_CMAKE_BUILD_TYPE} -DCMAKE_CXX_FLAGS=${DOLFINX_CMAKE_CXX_FLAGS} -B build-dir -S ./cpp
          cmake --build build-dir && cmake --install build-dir && python3 -m pip install ./python

      # Runs a set of commands using the runners shell
      - name: Install UFL and FFCx
        run: |
          python3 -m pip install git+https://github.com/FEniCS/ufl.git@jpdean/multiple_subdomain_data
          python3 -m pip install git+https://github.com/FEniCS/ffcx.git@jpdean/mixed_dim

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Flake8
        run: flake8 .
